### ISSUE TITLE
Bug при обработке ссылок закодированных base  64

### ISSUE THREAD

**Issue by 99kpv** [mihdan/mihdan-no-external-links#30]
С поддержкой admitad смотрели данную проблему

Вот их ответ

При размещении ссылок веб-мастер кодирует их в base  64, далее скорее всего отрабатывает JS скрип который приобразует при клике на ссылку преобразует ее. 
При приоразовании ссылки например: aHR0cHM6Ly9hZmxpbmsucnUvZy9rM2RmdmV2d2l0ZmE3Y2U3YTA0NTY1YTM3Y2EwM2QvP2k9MTAmIzAzODt1bHA9aHR0cHM6Ly9nYi5ydS9nZWVrX3VuaXZlcnNpdHkvZGV2ZWxvcGVyL3Byb2dyYW1tZXIvcHl0aG9u 
Получаем: 
https://aflink.ru/g/k3dfvevwitfa7ce7a04565a37ca03d/?i=10&#038;ulp=https://gb.ru/geek_university/developer/programmer/python 

Оригинальная ссылка выглядит вот так:
https://aflink.ru/g/k3dfvevwitfa7ce7a04565a37ca03d/?i=10&ulp=https://gb.ru/geek_university/developer/programmer/python

**Comment by mihdan** [comment]
По описанию надо на фронте делать аналог html_entity_decode.

Оставлю тут одно из решений

```javascript
function decodeHTMLEntities(text) {
  var textArea = document.createElement('textarea');
  textArea.innerHTML = text;
  return textArea.value;
}
```
